// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: AddChirpyRed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateChirpyRed = `-- name: UpdateChirpyRed :exec
UPDATE users
SET is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) UpdateChirpyRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateChirpyRed, id)
	return err
}
