// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetChirpUserId.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getChirpUserID = `-- name: GetChirpUserID :one
SELECT user_id FROM chirps WHERE id = $1
`

func (q *Queries) GetChirpUserID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getChirpUserID, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
