// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetHashByEmail.sql

package database

import (
	"context"
)

const getHashByEmail = `-- name: GetHashByEmail :one
SELECT id, created_at, updated_at, email, hashed_password FROM users WHERE email = $1
`

func (q *Queries) GetHashByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getHashByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
