// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: RevokeToken.sql

package database

import (
	"context"
)

const revokeToken = `-- name: RevokeToken :exec
UPDATE tokens
SET 
updated_at = NOW(),
revoked_at = NOW()
    
WHERE token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
