// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: UpdateInfo.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET 
updated_at = NOW(),
email = $1,
hashed_password = $2
    
WHERE id = $3
`

type UpdateUserParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Email, arg.HashedPassword, arg.ID)
	return err
}
